#include<stdio.h>
int main()
{
    int n,arr[100],i,j,c=0,dc=0,k;
    scanf("%d",&n);
    for(i=1;i<=n;i++)
    {
        scanf("%d",&arr[i]);
    }
    scanf("%d",&k);
    for(i=1;i<=n;i++)
    {
        c=0;
        for(j=1;j<=arr[i];j++)
        {
            if(arr[i]%j==0)
            {
               if(arr[i]<=k)
               {
                  c++;
               }
            }
        }
        if(c==2)
        {
            dc++;
        }
    }
    printf("%d",dc);
}